//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch FeuchteLuft.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PROPPAGE_MEDIUM             106
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_MOLLIERDIA_TYPE             130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_CALCULATION_TAB             300
#define IDS_PROCESS_TAB                 301
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_LAYERDLG                    310
#define IDD_PROPDLG                     313
#define IDD_CONFDLG                     315
#define IDD_STATEPOINTDLG               318
#define IDR_PROCESS						319
#define IDS_TOOLBAR_PROCESS				320
#define IDC_CHECK1                      1000
#define IDC_COMBO1                      1001
#define IDC_BUTTON1                     1002
#define IDC_CHECK2                      1003
#define IDC_COMBO2                      1004
#define IDC_BUTTON2                     1005
#define IDC_CHECK3                      1006
#define IDC_COMBO3                      1007
#define IDC_BUTTON3                     1008
#define IDC_CHECK4                      1009
#define IDC_COMBO4                      1010
#define IDC_BUTTON4                     1011
#define IDC_SPIN1                       1012
#define IDC_EDIT1                       1013
#define IDC_EDIT2                       1014
#define IDC_SPIN2                       1015
#define IDC_EDIT3                       1016
#define IDC_SPIN3                       1017
#define IDC_EDIT4                       1018
#define IDC_SPIN4                       1019
#define IDC_EDIT5                       1020
#define IDC_EDIT6                       1021
#define IDC_LIST1                       1022
#define ID_INDICATOR_X					32771
#define ID_INDICATOR_Y					32772
#define ID_PROCESS_AHU                  32773
#define ID_PROCESS_POINT                32774
#define ID_PROCESS_HEATER               32775
#define ID_PROCESS_COOLER               32776
#define ID_PROCESS_MIXER                32777
#define ID_PROCESS_HUMID                32778
#define ID_PROCESS_DEHUMID              32779
#define ID_PROCESS_RECUPERATION         32780
#define ID_PROCESS_REGENERATION         32781
#define ID_PROCESS_LOAD                 32782
#define ID_EXTRAS_CANCALC               32783
#define ID_EXTRAS_UMGEBUNG              32784
#define ID_EXTRAS_LAYER                 32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        322
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
